title: E2E Test Playbook
sections:
    - title: Transpilation Tests
      description:
        - Verify different types of TS scripts
      assertions:
        - code: PlainTest
          title: Plain Script
          description: Uses a plain script without imports or exports
          cmds:
            - exec:
                shellFunc: '"node";'
                func: ()=>"console.log('hello from plain')";
              exitCodeRules:
                - min: 0
                  max: 0
                  result: 1
          passDescription: Plain Script passed
          failDescription: Plain Script failed
        - code: ExportTest
          title: Export Script
          description: Uses export default
          cmds:
            - exec:
                func: |-
                    (function(){var exports={};var module={exports:exports};var t=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var p=Object.getOwnPropertyNames;var x=Object.prototype.hasOwnProperty;var a=(o,e)=>{for(var r in e)t(o,r,{get:e[r],enumerable:!0})},c=(o,e,r,f)=>{if(e&&typeof e=="object"||typeof e=="function")for(let l of p(e))!x.call(o,l)&&l!==r&&t(o,l,{get:()=>e[l],enumerable:!(f=h(e,l))||f.enumerable});return o};var d=o=>c(t({},"__esModule",{value:!0}),o);var u={};a(u,{default:()=>m});module.exports=d(u);var m=()=>"echo 'hello from export'";
                    ;return module.exports.default||module.exports})()
              exitCodeRules:
                - min: 0
                  max: 0
                  result: 1
          passDescription: Export Script passed
          failDescription: Export Script failed
        - code: ImportTypeTest
          title: Import Type Script
          description: Uses import type
          cmds:
            - exec:
                func: |-
                    (function(){var exports={};var module={exports:exports};var c=Object.defineProperty;var f=Object.getOwnPropertyDescriptor;var i=Object.getOwnPropertyNames;var l=Object.prototype.hasOwnProperty;var m=(t,o)=>{for(var r in o)c(t,r,{get:o[r],enumerable:!0})},n=(t,o,r,p)=>{if(o&&typeof o=="object"||typeof o=="function")for(let e of i(o))!l.call(t,e)&&e!==r&&c(t,e,{get:()=>o[e],enumerable:!(p=f(o,e))||p.enumerable});return t};var x=t=>n(c({},"__esModule",{value:!0}),t);var h={};m(h,{default:()=>d});module.exports=x(h);var d=({os:t})=>`echo 'hello from ${t}'`;
                    ;return module.exports.default||module.exports})()
              exitCodeRules:
                - min: 0
                  max: 0
                  result: 1
          passDescription: Import Type Script passed
          failDescription: Import Type Script failed
        - code: JSStateMachineTest
          title: JS State Machine
          description: 'Tests JS state across command stages: generate, increment, and verify'
          preCmds:
            - func: |
                () => {
                  const val = Math.floor(Math.random() * 1000);
                  return `echo ${val} > random_number1.txt`;
                }
          cmds:
            - exec:
                script: cat random_number1.txt
                gather:
                    - key: num1
                      regex: (\d+)
              passScore: 0
            - exec:
                func: |
                    ({ assertionContext }) => {
                      const nextVal = parseInt(assertionContext.num1) + 1;
                      return `echo ${nextVal} > random_number2.txt`;
                    }
              passScore: 0
            - exec:
                script: cat random_number2.txt
                gather:
                    - key: num2_secret
                      excludeFromReport: true
                      func: (stdout, stderr, assertionContext) => Number(stdout)
                excludeFromReport: true
            - exec:
                script: cat random_number1.txt && cat random_number2.txt
              stdOutRule:
                func: |
                    (stdout, stderr, assertionContext) => {
                      const ctxNum1 = Number(assertionContext.num1)
                      const ctxNum2 = Number(assertionContext.num2_secret)
                      if (ctxNum2 - ctxNum1 !== 1) return -1
                      const nums = stdout.trim().split(/\s+/).map(Number);
                      if (nums.length !== 2) return -1
                      return nums[0] === ctxNum1 && nums[1] === ctxNum2 ? 1 : -1
                    }
          postCmds:
            - shellFunc: () => '!'
              script: rm random_number2.txt
          passDescription: State machine correctly tracked and incremented the value across stages.
          failDescription: State machine failed to verify the incremented value.
